// 世界历史文明数据 - 精确复刻纸质版布局
// 坐标系统：x为像素位置，w为宽度，时间从上到下

const historyData = {
    civilizations: [
        // ===== 美索不达米亚/西亚文明 (最左列 x:0-120) =====
        { name: "苏美尔", nameEn: "SUMER", x: 0, w: 100, start: -3500, end: -2000, color: "#4a7c59", region: "westAsia",
          desc: "人类最早文明之一，楔形文字发明者", events: ["楔形文字发明", "城邦国家出现", "六十进制"] },
        { name: "古巴比伦", nameEn: "BABYLON", x: 0, w: 90, start: -1900, end: -1600, color: "#5d8a66", region: "westAsia",
          desc: "汉谟拉比法典诞生地", events: ["汉谟拉比法典", "巴比伦城"] },
        { name: "亚述帝国", nameEn: "ASSYRIA", x: 0, w: 85, start: -900, end: -612, color: "#3d6b4f", region: "westAsia",
          desc: "军事强国，铁器时代", events: ["尼尼微图书馆", "铁器应用"] },
        { name: "新巴比伦", nameEn: "NEO-BABYLON", x: 0, w: 70, start: -612, end: -539, color: "#5d8a66", region: "westAsia",
          desc: "空中花园", events: ["空中花园", "巴比伦之囚"] },
        { name: "波斯帝国", nameEn: "ACHAEMENID", x: 0, w: 120, start: -550, end: -330, color: "#2d5a3f", region: "westAsia",
          desc: "横跨亚欧非的第一个世界帝国", events: ["居鲁士大帝", "大流士改革", "波斯战争"] },
        { name: "塞琉古", nameEn: "SELEUCID", x: 10, w: 60, start: -312, end: -63, color: "#6b9b74", region: "westAsia",
          desc: "亚历山大帝国继承者", events: ["希腊化时代"] },
        { name: "帕提亚", nameEn: "PARTHIA", x: 0, w: 90, start: -247, end: 224, color: "#4a7c59", region: "westAsia",
          desc: "丝绸之路中转站", events: ["与罗马对峙", "安息帝国"] },
        { name: "萨珊波斯", nameEn: "SASSANID", x: 0, w: 100, start: 224, end: 651, color: "#2d5a3f", region: "westAsia",
          desc: "波斯帝国最后的辉煌", events: ["琐罗亚斯德教国教", "与罗马/拜占庭战争"] },
        { name: "倭马亚", nameEn: "UMAYYAD", x: 0, w: 80, start: 661, end: 750, color: "#5d8a66", region: "westAsia",
          desc: "阿拉伯帝国第一王朝", events: ["大马士革为都", "征服北非伊比利亚"] },
        { name: "阿拔斯", nameEn: "ABBASID", x: 0, w: 100, start: 750, end: 1258, color: "#4a7c59", region: "westAsia",
          desc: "伊斯兰黄金时代", events: ["巴格达为都", "阿拉伯数学天文"] },
        { name: "塞尔柱", nameEn: "SELJUK", x: 0, w: 70, start: 1037, end: 1194, color: "#3d6b4f", region: "westAsia",
          desc: "突厥帝国", events: ["控制巴格达", "十字军东征起因"] },
        { name: "伊尔汗国", nameEn: "ILKHANATE", x: 0, w: 80, start: 1256, end: 1335, color: "#6b9b74", region: "westAsia",
          desc: "蒙古四大汗国之一", events: ["旭烈兀西征", "灭阿拔斯"] },
        { name: "帖木儿", nameEn: "TIMURID", x: 0, w: 70, start: 1370, end: 1507, color: "#5d8a66", region: "westAsia",
          desc: "帖木儿帝国", events: ["撒马尔罕", "文化复兴"] },
        { name: "萨法维", nameEn: "SAFAVID", x: 0, w: 90, start: 1501, end: 1736, color: "#2d5a3f", region: "westAsia",
          desc: "什叶派波斯", events: ["什叶派国教", "伊斯法罕"] },
        { name: "恺加王朝", nameEn: "QAJAR", x: 0, w: 70, start: 1789, end: 1925, color: "#4a7c59", region: "westAsia",
          desc: "近代伊朗", events: ["德黑兰为都"] },
        { name: "巴列维", nameEn: "PAHLAVI", x: 0, w: 60, start: 1925, end: 1979, color: "#5d8a66", region: "westAsia",
          desc: "伊朗现代化", events: ["白色革命"] },
        { name: "伊朗", nameEn: "IRAN", x: 0, w: 60, start: 1979, end: 2024, color: "#3d6b4f", region: "westAsia",
          desc: "伊斯兰共和国", events: ["伊斯兰革命"] },

        // ===== 奥斯曼帝国 (跨西亚和欧洲 x:80-180) =====
        { name: "奥斯曼帝国", nameEn: "OTTOMAN EMPIRE", x: 80, w: 100, start: 1299, end: 1922, color: "#c0392b", region: "westAsia",
          desc: "横跨欧亚非的伊斯兰帝国", events: ["攻陷君士坦丁堡", "苏莱曼大帝", "一战解体"] },

        // ===== 南亚文明 (x:130-250) =====
        { name: "印度河文明", nameEn: "INDUS VALLEY", x: 130, w: 100, start: -2600, end: -1900, color: "#2980b9", region: "southAsia",
          desc: "世界四大古文明之一", events: ["哈拉帕", "摩亨佐达罗", "城市规划"] },
        { name: "吠陀时代", nameEn: "VEDIC PERIOD", x: 140, w: 80, start: -1500, end: -500, color: "#3498db", region: "southAsia",
          desc: "雅利安人入侵，种姓制度形成", events: ["吠陀经典", "婆罗门教", "种姓制度"] },
        { name: "孔雀王朝", nameEn: "MAURYA", x: 130, w: 90, start: -321, end: -185, color: "#2980b9", region: "southAsia",
          desc: "印度第一个统一帝国", events: ["阿育王", "佛教传播", "狮子柱头"] },
        { name: "贵霜帝国", nameEn: "KUSHAN", x: 140, w: 70, start: 30, end: 375, color: "#3498db", region: "southAsia",
          desc: "丝绸之路重镇", events: ["犍陀罗艺术", "佛教大乘派"] },
        { name: "笈多王朝", nameEn: "GUPTA", x: 130, w: 90, start: 320, end: 550, color: "#2980b9", region: "southAsia",
          desc: "印度古典黄金时代", events: ["印度教复兴", "阿拉伯数字起源", "文学艺术繁荣"] },
        { name: "德里苏丹", nameEn: "DELHI SULTANATE", x: 140, w: 80, start: 1206, end: 1526, color: "#1abc9c", region: "southAsia",
          desc: "伊斯兰统治印度北部", events: ["德里为都", "印度伊斯兰文化"] },
        { name: "莫卧儿帝国", nameEn: "MUGHAL EMPIRE", x: 120, w: 110, start: 1526, end: 1857, color: "#16a085", region: "southAsia",
          desc: "印度最强盛的伊斯兰帝国", events: ["巴布尔建国", "阿克巴大帝", "泰姬陵"] },
        { name: "英属印度", nameEn: "BRITISH INDIA", x: 140, w: 80, start: 1858, end: 1947, color: "#7f8c8d", region: "southAsia",
          desc: "英国殖民统治", events: ["东印度公司", "印度民族起义", "甘地运动"] },
        { name: "印度", nameEn: "INDIA", x: 140, w: 80, start: 1947, end: 2024, color: "#f39c12", region: "southAsia",
          desc: "世界最大民主国家", events: ["印巴分治", "不结盟运动", "IT大国"] },

        // ===== 蒙古游牧文明 (x:240-340) =====
        { name: "匈奴", nameEn: "XIONGNU", x: 250, w: 70, start: -209, end: 93, color: "#8d6e63", region: "mongol",
          desc: "草原霸主", events: ["冒顿单于统一", "白登之围", "和亲政策"] },
        { name: "鲜卑", nameEn: "XIANBEI", x: 250, w: 60, start: 93, end: 234, color: "#795548", region: "mongol",
          desc: "继匈奴崛起", events: ["檀石槐统一", "后建北魏"] },
        { name: "柔然", nameEn: "ROURAN", x: 250, w: 60, start: 330, end: 555, color: "#a1887f", region: "mongol",
          desc: "与北魏对峙", events: ["控制草原", "被突厥所灭"] },
        { name: "突厥汗国", nameEn: "TURKIC", x: 240, w: 80, start: 552, end: 744, color: "#8d6e63", region: "mongol",
          desc: "突厥帝国", events: ["控制丝路", "东西突厥分裂"] },
        { name: "回鹘", nameEn: "UYGHUR", x: 250, w: 60, start: 744, end: 840, color: "#795548", region: "mongol",
          desc: "回鹘汗国", events: ["助唐平安史之乱"] },
        { name: "蒙古帝国", nameEn: "MONGOL EMPIRE", x: 220, w: 130, start: 1206, end: 1368, color: "#5d4037", region: "mongol",
          desc: "人类历史最大陆地帝国", events: ["成吉思汗统一", "三次西征", "四大汗国"] },
        { name: "蒙古", nameEn: "MONGOLIA", x: 260, w: 50, start: 1911, end: 2024, color: "#8d6e63", region: "mongol",
          desc: "现代蒙古国", events: ["独立", "社会主义", "民主化"] },

        // ===== 中华文明 (核心 x:340-550) =====
        { name: "夏", nameEn: "XIA", x: 380, w: 100, start: -2070, end: -1600, color: "#c23531", region: "china",
          desc: "中国第一个世袭制王朝", events: ["禹建夏朝", "启继位开世袭", "太康失国"] },
        { name: "商", nameEn: "SHANG", x: 370, w: 110, start: -1600, end: -1046, color: "#d35400", region: "china",
          desc: "甲骨文青铜器", events: ["盘庚迁殷", "甲骨文", "青铜鼎盛"] },
        { name: "西周", nameEn: "WESTERN ZHOU", x: 360, w: 120, start: -1046, end: -771, color: "#c23531", region: "china",
          desc: "分封制礼乐制", events: ["武王伐纣", "周公制礼", "分封诸侯"] },
        { name: "东周", nameEn: "EASTERN ZHOU", x: 370, w: 100, start: -770, end: -256, color: "#e74c3c", region: "china",
          desc: "春秋战国百家争鸣", events: ["春秋五霸", "战国七雄", "诸子百家"] },
        { name: "秦", nameEn: "QIN", x: 350, w: 130, start: -221, end: -206, color: "#2c3e50", region: "china",
          desc: "首个统一帝国", events: ["始皇统一", "书同文车同轨", "万里长城"] },
        { name: "西汉", nameEn: "WESTERN HAN", x: 340, w: 150, start: -206, end: 9, color: "#c23531", region: "china",
          desc: "汉武盛世丝绸之路", events: ["刘邦建汉", "文景之治", "武帝开疆", "张骞通西域"] },
        { name: "新", nameEn: "XIN", x: 400, w: 40, start: 9, end: 23, color: "#7f8c8d", region: "china",
          desc: "王莽篡汉", events: ["王莽改制", "绿林赤眉"] },
        { name: "东汉", nameEn: "EASTERN HAN", x: 340, w: 150, start: 25, end: 220, color: "#c23531", region: "china",
          desc: "光武中兴", events: ["光武中兴", "造纸术改进", "佛教东传", "黄巾起义"] },
        { name: "三国", nameEn: "THREE KINGDOMS", x: 360, w: 110, start: 220, end: 280, color: "#34495e", region: "china",
          desc: "魏蜀吴鼎立", events: ["曹魏", "蜀汉", "东吴", "英雄辈出"] },
        { name: "西晋", nameEn: "WESTERN JIN", x: 370, w: 90, start: 265, end: 316, color: "#95a5a6", region: "china",
          desc: "短暂统一", events: ["司马炎统一", "八王之乱", "永嘉之乱"] },
        { name: "东晋", nameEn: "EASTERN JIN", x: 400, w: 70, start: 317, end: 420, color: "#bdc3c7", region: "china",
          desc: "偏安江南", events: ["衣冠南渡", "淝水之战", "门阀政治"] },
        { name: "南北朝", nameEn: "N&S DYNASTIES", x: 350, w: 130, start: 420, end: 589, color: "#e67e22", region: "china",
          desc: "民族大融合", events: ["南朝四代", "北魏孝文帝改革", "佛教大兴"] },
        { name: "隋", nameEn: "SUI", x: 350, w: 130, start: 581, end: 618, color: "#d35400", region: "china",
          desc: "统一开科举修运河", events: ["隋文帝统一", "科举创立", "大运河"] },
        { name: "唐", nameEn: "TANG", x: 320, w: 180, start: 618, end: 907, color: "#c23531", region: "china",
          desc: "盛唐气象万国来朝", events: ["贞观之治", "开元盛世", "安史之乱", "唐诗繁荣"] },
        { name: "五代", nameEn: "FIVE DYNASTIES", x: 380, w: 80, start: 907, end: 960, color: "#7f8c8d", region: "china",
          desc: "分裂割据", events: ["后梁后唐后晋后汉后周"] },
        { name: "辽", nameEn: "LIAO", x: 320, w: 60, start: 916, end: 1125, color: "#3498db", region: "china",
          desc: "契丹建国", events: ["耶律阿保机", "澶渊之盟"] },
        { name: "北宋", nameEn: "NORTHERN SONG", x: 380, w: 100, start: 960, end: 1127, color: "#c23531", region: "china",
          desc: "文化经济繁荣", events: ["杯酒释兵权", "王安石变法", "活字印刷"] },
        { name: "西夏", nameEn: "WESTERN XIA", x: 320, w: 50, start: 1038, end: 1227, color: "#1abc9c", region: "china",
          desc: "党项建国", events: ["李元昊称帝", "西夏文字"] },
        { name: "金", nameEn: "JIN", x: 320, w: 60, start: 1115, end: 1234, color: "#f39c12", region: "china",
          desc: "女真建国", events: ["完颜阿骨打", "靖康之变"] },
        { name: "南宋", nameEn: "SOUTHERN SONG", x: 400, w: 80, start: 1127, end: 1279, color: "#e74c3c", region: "china",
          desc: "偏安临安", events: ["岳飞抗金", "理学兴盛", "经济繁荣"] },
        { name: "元", nameEn: "YUAN", x: 310, w: 180, start: 1271, end: 1368, color: "#2c3e50", region: "china",
          desc: "蒙元入主", events: ["忽必烈建元", "行省制度", "海上丝路"] },
        { name: "明", nameEn: "MING", x: 320, w: 180, start: 1368, end: 1644, color: "#c23531", region: "china",
          desc: "最后汉族王朝", events: ["朱元璋建明", "郑和下西洋", "永乐盛世", "万历怠政"] },
        { name: "清", nameEn: "QING", x: 300, w: 200, start: 1644, end: 1912, color: "#f39c12", region: "china",
          desc: "最后封建王朝", events: ["康乾盛世", "闭关锁国", "鸦片战争", "辛亥革命"] },
        { name: "中华民国", nameEn: "ROC", x: 360, w: 100, start: 1912, end: 1949, color: "#3498db", region: "china",
          desc: "亚洲第一共和国", events: ["辛亥革命", "北伐统一", "抗日战争"] },
        { name: "中华人民共和国", nameEn: "PRC", x: 320, w: 180, start: 1949, end: 2024, color: "#c23531", region: "china",
          desc: "社会主义国家", events: ["新中国成立", "改革开放", "复兴之路"] },

        // ===== 欧洲文明 (x:520-700) =====
        { name: "古希腊", nameEn: "ANCIENT GREECE", x: 540, w: 100, start: -800, end: -146, color: "#f39c12", region: "europe",
          desc: "西方文明摇篮", events: ["雅典民主", "斯巴达", "亚历山大东征"] },
        { name: "罗马共和国", nameEn: "ROMAN REPUBLIC", x: 530, w: 110, start: -509, end: -27, color: "#e67e22", region: "europe",
          desc: "共和制典范", events: ["十二铜表法", "布匿战争", "恺撒崛起"] },
        { name: "罗马帝国", nameEn: "ROMAN EMPIRE", x: 520, w: 140, start: -27, end: 476, color: "#d35400", region: "europe",
          desc: "地中海霸主", events: ["奥古斯都", "罗马和平", "基督教国教", "西罗马灭亡"] },
        { name: "拜占庭帝国", nameEn: "BYZANTINE", x: 580, w: 100, start: 395, end: 1453, color: "#9b59b6", region: "europe",
          desc: "东罗马千年", events: ["查士丁尼", "希腊火", "君士坦丁堡陷落"] },
        { name: "法兰克王国", nameEn: "FRANKISH", x: 520, w: 80, start: 481, end: 843, color: "#3498db", region: "europe",
          desc: "西欧封建起源", events: ["克洛维", "查理曼大帝", "凡尔登条约"] },
        { name: "神圣罗马帝国", nameEn: "HRE", x: 520, w: 90, start: 962, end: 1806, color: "#e67e22", region: "europe",
          desc: "德意志神圣罗马帝国", events: ["奥托一世", "宗教改革", "三十年战争"] },
        { name: "英格兰", nameEn: "ENGLAND", x: 620, w: 60, start: 927, end: 1707, color: "#3498db", region: "europe",
          desc: "不列颠岛国", events: ["诺曼征服", "大宪章", "百年战争", "都铎王朝"] },
        { name: "法兰西", nameEn: "FRANCE", x: 540, w: 80, start: 843, end: 1792, color: "#2980b9", region: "europe",
          desc: "欧陆强国", events: ["卡佩王朝", "路易十四", "启蒙运动"] },
        { name: "西班牙帝国", nameEn: "SPANISH EMPIRE", x: 520, w: 100, start: 1492, end: 1898, color: "#f39c12", region: "europe",
          desc: "日不落先驱", events: ["收复失地", "发现新大陆", "无敌舰队"] },
        { name: "大英帝国", nameEn: "BRITISH EMPIRE", x: 600, w: 100, start: 1707, end: 1997, color: "#e74c3c", region: "europe",
          desc: "日不落帝国", events: ["工业革命", "维多利亚", "两次大战"] },
        { name: "法国", nameEn: "FRANCE", x: 540, w: 80, start: 1792, end: 2024, color: "#3498db", region: "europe",
          desc: "共和国", events: ["大革命", "拿破仑", "欧盟创始"] },
        { name: "德意志", nameEn: "GERMANY", x: 520, w: 80, start: 1871, end: 1945, color: "#7f8c8d", region: "europe",
          desc: "德意志帝国", events: ["俾斯麦统一", "一战", "纳粹", "二战"] },
        { name: "苏联", nameEn: "USSR", x: 620, w: 80, start: 1922, end: 1991, color: "#c0392b", region: "europe",
          desc: "第一个社会主义国家", events: ["十月革命", "斯大林", "冷战", "解体"] },
        { name: "德国", nameEn: "GERMANY", x: 520, w: 80, start: 1990, end: 2024, color: "#2c3e50", region: "europe",
          desc: "统一后德国", events: ["柏林墙倒塌", "欧盟核心"] },
        { name: "俄罗斯", nameEn: "RUSSIA", x: 620, w: 80, start: 1991, end: 2024, color: "#3498db", region: "europe",
          desc: "俄罗斯联邦", events: ["苏联解体", "普京时代"] },

        // ===== 非洲文明 (x:710-800) =====
        { name: "古埃及", nameEn: "ANCIENT EGYPT", x: 710, w: 90, start: -3100, end: -30, color: "#8e44ad", region: "africa",
          desc: "尼罗河文明", events: ["金字塔", "法老", "象形文字", "木乃伊"] },
        { name: "库什", nameEn: "KUSH", x: 720, w: 60, start: -1070, end: 350, color: "#9b59b6", region: "africa",
          desc: "努比亚王国", events: ["第25王朝", "麦罗埃文化"] },
        { name: "迦太基", nameEn: "CARTHAGE", x: 710, w: 70, start: -814, end: -146, color: "#8e44ad", region: "africa",
          desc: "腓尼基殖民地", events: ["汉尼拔", "布匿战争", "罗马灭迦太基"] },
        { name: "阿克苏姆", nameEn: "AKSUM", x: 720, w: 60, start: 100, end: 940, color: "#9b59b6", region: "africa",
          desc: "埃塞俄比亚古国", events: ["皈依基督教", "贸易繁荣"] },
        { name: "加纳帝国", nameEn: "GHANA", x: 710, w: 70, start: 700, end: 1240, color: "#8e44ad", region: "africa",
          desc: "西非黄金帝国", events: ["跨撒哈拉贸易", "黄金之国"] },
        { name: "马里帝国", nameEn: "MALI", x: 710, w: 80, start: 1235, end: 1600, color: "#9b59b6", region: "africa",
          desc: "西非最富帝国", events: ["曼萨穆萨", "廷巴克图", "黄金朝圣"] },
        { name: "桑海帝国", nameEn: "SONGHAI", x: 720, w: 60, start: 1464, end: 1591, color: "#8e44ad", region: "africa",
          desc: "西非最后大帝国", events: ["索尼阿里", "廷巴克图"] },
        { name: "埃及", nameEn: "EGYPT", x: 720, w: 60, start: 1953, end: 2024, color: "#9b59b6", region: "africa",
          desc: "现代埃及", events: ["纳赛尔革命", "苏伊士运河"] },

        // ===== 美洲文明 (x:810-900) =====
        { name: "奥尔梅克", nameEn: "OLMEC", x: 820, w: 60, start: -1500, end: -400, color: "#16a085", region: "americas",
          desc: "中美洲母文明", events: ["巨石头像", "历法文字起源"] },
        { name: "玛雅", nameEn: "MAYA", x: 810, w: 80, start: -2000, end: 1500, color: "#1abc9c", region: "americas",
          desc: "中美洲古典文明", events: ["玛雅历法", "象形文字", "金字塔"] },
        { name: "特奥蒂瓦坎", nameEn: "TEOTIHUACAN", x: 820, w: 60, start: 100, end: 750, color: "#16a085", region: "americas",
          desc: "众神之城", events: ["太阳金字塔", "月亮金字塔"] },
        { name: "阿兹特克", nameEn: "AZTEC", x: 810, w: 70, start: 1345, end: 1521, color: "#1abc9c", region: "americas",
          desc: "墨西哥帝国", events: ["特诺奇蒂特兰", "活人祭祀", "科尔特斯征服"] },
        { name: "印加", nameEn: "INCA", x: 820, w: 60, start: 1438, end: 1533, color: "#16a085", region: "americas",
          desc: "安第斯帝国", events: ["库斯科", "马丘比丘", "结绳记事"] },
        { name: "美国", nameEn: "USA", x: 810, w: 90, start: 1776, end: 2024, color: "#3498db", region: "americas",
          desc: "超级大国", events: ["独立宣言", "南北战争", "两次大战", "冷战胜利"] },
        { name: "墨西哥", nameEn: "MEXICO", x: 820, w: 50, start: 1821, end: 2024, color: "#27ae60", region: "americas",
          desc: "拉美大国", events: ["独立", "革命"] },
        { name: "巴西", nameEn: "BRAZIL", x: 870, w: 50, start: 1822, end: 2024, color: "#f1c40f", region: "americas",
          desc: "南美最大国", events: ["独立", "经济起飞"] }
    ]
};

// 地区名称
const regionNames = {
    china: "中华文明",
    southAsia: "南亚文明",
    westAsia: "西亚/波斯文明",
    europe: "欧洲文明",
    africa: "非洲文明",
    americas: "美洲文明",
    mongol: "蒙古游牧文明"
};
