// 世界历史文明数据 - 按照纸质版精确布局
// 坐标系统：x为列位置(0-1000)，宽度为相对宽度

const historyData = {
    // 地区列定义（从左到右）
    columns: {
        mesopotamia: { x: 0, name: "美索不达米亚文明", nameEn: "MESOPOTAMIA" },
        persia: { x: 100, name: "波斯文明", nameEn: "PERSIA" },
        southAsia: { x: 200, name: "南亚文明", nameEn: "SOUTH ASIA" },
        mongol: { x: 350, name: "蒙古游牧文明", nameEn: "MONGOL" },
        china: { x: 500, name: "中华文明", nameEn: "CHINA" },
        europe: { x: 650, name: "欧洲文明", nameEn: "EUROPE" },
        africa: { x: 800, name: "非洲文明", nameEn: "AFRICA" },
        americas: { x: 900, name: "美洲文明", nameEn: "AMERICAS" }
    },

    // 文明数据 - 精确定义位置和大小
    civilizations: [
        // ========== 中华文明 ==========
        { name: "夏", nameEn: "XIA", x: 520, w: 80, start: -2070, end: -1600, color: "#c23531", region: "china",
          desc: "中国第一个世袭制王朝", events: ["禹建立夏朝", "启继位，世袭制开始"] },
        { name: "商", nameEn: "SHANG", x: 520, w: 80, start: -1600, end: -1046, color: "#d48265", region: "china",
          desc: "甲骨文出现，青铜器鼎盛", events: ["盘庚迁殷", "甲骨文成熟", "青铜器铸造发达"] },
        { name: "西周", nameEn: "W.ZHOU", x: 520, w: 80, start: -1046, end: -771, color: "#91c7ae", region: "china",
          desc: "分封制和礼乐制度", events: ["武王伐纣", "周公制礼作乐", "分封诸侯"] },
        { name: "东周", nameEn: "E.ZHOU", x: 520, w: 60, start: -770, end: -256, color: "#749f83", region: "china",
          desc: "春秋战国，百家争鸣", events: ["春秋五霸", "战国七雄", "诸子百家"] },
        { name: "秦", nameEn: "QIN", x: 500, w: 100, start: -221, end: -206, color: "#2c3e50", region: "china",
          desc: "中国首个统一帝国", events: ["统一六国", "统一文字度量衡", "修长城"] },
        { name: "西汉", nameEn: "W.HAN", x: 480, w: 120, start: -206, end: 9, color: "#c23531", region: "china",
          desc: "丝绸之路开通", events: ["刘邦建汉", "文景之治", "张骞通西域"] },
        { name: "新", nameEn: "XIN", x: 540, w: 40, start: 9, end: 23, color: "#999", region: "china",
          desc: "王莽篡汉", events: ["王莽改制"] },
        { name: "东汉", nameEn: "E.HAN", x: 480, w: 120, start: 25, end: 220, color: "#c23531", region: "china",
          desc: "造纸术改进，佛教传入", events: ["光武中兴", "蔡伦改进造纸术", "佛教传入"] },
        { name: "三国", nameEn: "THREE KINGDOMS", x: 500, w: 100, start: 220, end: 280, color: "#61a0a8", region: "china",
          desc: "魏蜀吴三国鼎立", events: ["曹丕称帝", "刘备建蜀", "孙权建吴"] },
        { name: "西晋", nameEn: "W.JIN", x: 520, w: 80, start: 265, end: 316, color: "#749f83", region: "china",
          desc: "短暂统一后八王之乱", events: ["司马炎统一", "八王之乱"] },
        { name: "东晋", nameEn: "E.JIN", x: 540, w: 60, start: 317, end: 420, color: "#91c7ae", region: "china",
          desc: "偏安江南", events: ["司马睿南渡", "淝水之战"] },
        { name: "南北朝", nameEn: "N&S DYNASTIES", x: 500, w: 100, start: 420, end: 589, color: "#d48265", region: "china",
          desc: "民族大融合", events: ["南朝四代", "北魏孝文帝改革"] },
        { name: "隋", nameEn: "SUI", x: 500, w: 100, start: 581, end: 618, color: "#ca8622", region: "china",
          desc: "大运河开通，科举创立", events: ["统一南北", "开科举", "修大运河"] },
        { name: "唐", nameEn: "TANG", x: 460, w: 160, start: 618, end: 907, color: "#c23531", region: "china",
          desc: "盛唐气象，万国来朝", events: ["贞观之治", "开元盛世", "安史之乱"] },
        { name: "五代十国", nameEn: "FIVE DYNASTIES", x: 520, w: 80, start: 907, end: 960, color: "#999", region: "china",
          desc: "分裂割据", events: ["后梁后唐后晋后汉后周", "十国割据"] },
        { name: "北宋", nameEn: "N.SONG", x: 500, w: 100, start: 960, end: 1127, color: "#c23531", region: "china",
          desc: "经济文化繁荣", events: ["杯酒释兵权", "王安石变法", "活字印刷"] },
        { name: "辽", nameEn: "LIAO", x: 420, w: 60, start: 916, end: 1125, color: "#61a0a8", region: "china",
          desc: "契丹建立", events: ["耶律阿保机建国"] },
        { name: "西夏", nameEn: "W.XIA", x: 420, w: 50, start: 1038, end: 1227, color: "#749f83", region: "china",
          desc: "党项建立", events: ["李元昊称帝"] },
        { name: "金", nameEn: "JIN", x: 420, w: 60, start: 1115, end: 1234, color: "#ca8622", region: "china",
          desc: "女真建立", events: ["完颜阿骨打建国", "灭北宋"] },
        { name: "南宋", nameEn: "S.SONG", x: 520, w: 80, start: 1127, end: 1279, color: "#c23531", region: "china",
          desc: "偏安江南", events: ["岳飞抗金", "理学兴盛"] },
        { name: "元", nameEn: "YUAN", x: 440, w: 140, start: 1271, end: 1368, color: "#2f4554", region: "china",
          desc: "蒙古帝国在华", events: ["忽必烈建元", "行省制度"] },
        { name: "明", nameEn: "MING", x: 460, w: 160, start: 1368, end: 1644, color: "#c23531", region: "china",
          desc: "郑和下西洋", events: ["朱元璋建明", "郑和下西洋", "永乐盛世"] },
        { name: "清", nameEn: "QING", x: 440, w: 180, start: 1644, end: 1912, color: "#ca8622", region: "china",
          desc: "康乾盛世，后遭列强入侵", events: ["康熙平三藩", "乾隆盛世", "鸦片战争"] },
        { name: "中华民国", nameEn: "ROC", x: 500, w: 100, start: 1912, end: 1949, color: "#61a0a8", region: "china",
          desc: "亚洲第一个共和国", events: ["辛亥革命", "北伐战争", "抗日战争"] },
        { name: "中华人民共和国", nameEn: "PRC", x: 460, w: 160, start: 1949, end: 2024, color: "#c23531", region: "china",
          desc: "社会主义国家", events: ["新中国成立", "改革开放", "一带一路"] },

        // ========== 波斯/西亚文明 ==========
        { name: "苏美尔", nameEn: "SUMER", x: 20, w: 80, start: -3500, end: -2000, color: "#2ecc71", region: "westAsia",
          desc: "人类最早文明之一", events: ["楔形文字", "城邦国家"] },
        { name: "古巴比伦", nameEn: "BABYLON", x: 30, w: 70, start: -1894, end: -1595, color: "#27ae60", region: "westAsia",
          desc: "汉谟拉比法典", events: ["汉谟拉比法典", "空中花园传说"] },
        { name: "亚述", nameEn: "ASSYRIA", x: 20, w: 80, start: -911, end: -609, color: "#16a085", region: "westAsia",
          desc: "军事强国", events: ["铁器应用", "尼尼微图书馆"] },
        { name: "新巴比伦", nameEn: "NEO-BABYLON", x: 40, w: 60, start: -626, end: -539, color: "#27ae60", region: "westAsia",
          desc: "空中花园", events: ["尼布甲尼撒二世", "巴比伦之囚"] },
        { name: "波斯帝国", nameEn: "PERSIAN EMPIRE", x: 10, w: 120, start: -550, end: -330, color: "#2ecc71", region: "westAsia",
          desc: "横跨亚欧非的大帝国", events: ["居鲁士大帝", "大流士改革", "波斯战争"] },
        { name: "塞琉古", nameEn: "SELEUCID", x: 40, w: 60, start: -312, end: -63, color: "#1abc9c", region: "westAsia",
          desc: "希腊化王国", events: ["亚历山大遗产"] },
        { name: "帕提亚", nameEn: "PARTHIA", x: 30, w: 80, start: -247, end: 224, color: "#16a085", region: "westAsia",
          desc: "丝路中转站", events: ["与罗马对峙"] },
        { name: "萨珊波斯", nameEn: "SASSANID", x: 20, w: 100, start: 224, end: 651, color: "#27ae60", region: "westAsia",
          desc: "波斯最后辉煌", events: ["琐罗亚斯德教", "与罗马战争"] },
        { name: "倭马亚王朝", nameEn: "UMAYYAD", x: 30, w: 80, start: 661, end: 750, color: "#2ecc71", region: "westAsia",
          desc: "伊斯兰扩张", events: ["大马士革为都", "征服北非"] },
        { name: "阿拔斯王朝", nameEn: "ABBASID", x: 20, w: 100, start: 750, end: 1258, color: "#27ae60", region: "westAsia",
          desc: "伊斯兰黄金时代", events: ["巴格达为都", "阿拉伯数字"] },
        { name: "塞尔柱帝国", nameEn: "SELJUK", x: 40, w: 70, start: 1037, end: 1194, color: "#16a085", region: "westAsia",
          desc: "突厥帝国", events: ["曼齐刻尔特战役"] },
        { name: "伊尔汗国", nameEn: "ILKHANATE", x: 30, w: 80, start: 1256, end: 1335, color: "#1abc9c", region: "westAsia",
          desc: "蒙古西征建立", events: ["旭烈兀建立"] },
        { name: "帖木儿帝国", nameEn: "TIMURID", x: 40, w: 70, start: 1370, end: 1507, color: "#2ecc71", region: "westAsia",
          desc: "帖木儿征服", events: ["撒马尔罕为都"] },
        { name: "萨法维王朝", nameEn: "SAFAVID", x: 20, w: 100, start: 1501, end: 1736, color: "#27ae60", region: "westAsia",
          desc: "什叶派伊朗", events: ["伊斯法罕为都", "什叶派国教"] },
        { name: "奥斯曼帝国", nameEn: "OTTOMAN", x: 100, w: 100, start: 1299, end: 1922, color: "#e74c3c", region: "westAsia",
          desc: "横跨三洲的帝国", events: ["攻陷君士坦丁堡", "苏莱曼大帝"] },
        { name: "恺加王朝", nameEn: "QAJAR", x: 40, w: 60, start: 1789, end: 1925, color: "#16a085", region: "westAsia",
          desc: "近代伊朗", events: ["德黑兰为都"] },
        { name: "巴列维王朝", nameEn: "PAHLAVI", x: 50, w: 50, start: 1925, end: 1979, color: "#2ecc71", region: "westAsia",
          desc: "伊朗现代化", events: ["白色革命"] },
        { name: "伊朗", nameEn: "IRAN", x: 50, w: 50, start: 1979, end: 2024, color: "#27ae60", region: "westAsia",
          desc: "伊斯兰共和国", events: ["伊斯兰革命"] },

        // ========== 南亚文明 ==========
        { name: "印度河文明", nameEn: "INDUS", x: 220, w: 80, start: -2600, end: -1900, color: "#3498db", region: "southAsia",
          desc: "四大古文明之一", events: ["哈拉帕文明", "摩亨佐达罗"] },
        { name: "吠陀时代", nameEn: "VEDIC", x: 230, w: 70, start: -1500, end: -500, color: "#2980b9", region: "southAsia",
          desc: "雅利安人时代", events: ["吠陀经典", "种姓制度"] },
        { name: "孔雀王朝", nameEn: "MAURYA", x: 220, w: 80, start: -321, end: -185, color: "#3498db", region: "southAsia",
          desc: "印度首个统一帝国", events: ["阿育王", "佛教传播"] },
        { name: "贵霜帝国", nameEn: "KUSHAN", x: 230, w: 70, start: 30, end: 375, color: "#2980b9", region: "southAsia",
          desc: "丝路重镇", events: ["犍陀罗艺术", "佛教大乘"] },
        { name: "笈多王朝", nameEn: "GUPTA", x: 220, w: 80, start: 320, end: 550, color: "#3498db", region: "southAsia",
          desc: "印度古典黄金时代", events: ["印度教复兴", "阿拉伯数字起源"] },
        { name: "戒日王朝", nameEn: "HARSHA", x: 240, w: 50, start: 606, end: 647, color: "#2980b9", region: "southAsia",
          desc: "玄奘西游目的地", events: ["玄奘访印"] },
        { name: "德里苏丹国", nameEn: "DELHI SULTANATE", x: 220, w: 80, start: 1206, end: 1526, color: "#1abc9c", region: "southAsia",
          desc: "伊斯兰统治印度", events: ["德里为都", "印度伊斯兰文化"] },
        { name: "莫卧儿帝国", nameEn: "MUGHAL", x: 200, w: 120, start: 1526, end: 1857, color: "#16a085", region: "southAsia",
          desc: "印度最强盛的伊斯兰帝国", events: ["泰姬陵", "阿克巴大帝"] },
        { name: "英属印度", nameEn: "BRITISH INDIA", x: 220, w: 80, start: 1858, end: 1947, color: "#95a5a6", region: "southAsia",
          desc: "英国殖民统治", events: ["东印度公司", "甘地运动"] },
        { name: "印度", nameEn: "INDIA", x: 220, w: 80, start: 1947, end: 2024, color: "#f39c12", region: "southAsia",
          desc: "世界最大民主国家", events: ["印巴分治", "IT强国"] },

        // ========== 欧洲文明 ==========
        { name: "古希腊", nameEn: "ANCIENT GREECE", x: 660, w: 80, start: -800, end: -146, color: "#f39c12", region: "europe",
          desc: "西方文明摇篮", events: ["雅典民主", "苏格拉底柏拉图亚里士多德"] },
        { name: "罗马共和国", nameEn: "ROMAN REPUBLIC", x: 650, w: 100, start: -509, end: -27, color: "#e67e22", region: "europe",
          desc: "共和制典范", events: ["十二铜表法", "布匿战争"] },
        { name: "罗马帝国", nameEn: "ROMAN EMPIRE", x: 640, w: 120, start: -27, end: 476, color: "#d35400", region: "europe",
          desc: "地中海霸主", events: ["奥古斯都", "基督教传播", "帝国分裂"] },
        { name: "拜占庭帝国", nameEn: "BYZANTINE", x: 680, w: 80, start: 395, end: 1453, color: "#9b59b6", region: "europe",
          desc: "东罗马帝国", events: ["查士丁尼", "君士坦丁堡陷落"] },
        { name: "法兰克王国", nameEn: "FRANKISH", x: 650, w: 70, start: 481, end: 843, color: "#3498db", region: "europe",
          desc: "西欧封建起源", events: ["查理曼大帝", "凡尔登条约"] },
        { name: "神圣罗马帝国", nameEn: "HRE", x: 660, w: 80, start: 962, end: 1806, color: "#e67e22", region: "europe",
          desc: "德意志神圣罗马帝国", events: ["奥托一世", "三十年战争"] },
        { name: "英格兰", nameEn: "ENGLAND", x: 750, w: 60, start: 927, end: 1707, color: "#3498db", region: "europe",
          desc: "不列颠岛国", events: ["诺曼征服", "大宪章", "百年战争"] },
        { name: "法兰西王国", nameEn: "FRANCE", x: 680, w: 70, start: 843, end: 1792, color: "#2980b9", region: "europe",
          desc: "欧洲大陆强国", events: ["百年战争", "路易十四"] },
        { name: "西班牙帝国", nameEn: "SPANISH EMPIRE", x: 640, w: 90, start: 1492, end: 1898, color: "#f39c12", region: "europe",
          desc: "日不落帝国先驱", events: ["哥伦布发现新大陆", "无敌舰队"] },
        { name: "大英帝国", nameEn: "BRITISH EMPIRE", x: 720, w: 100, start: 1707, end: 1997, color: "#e74c3c", region: "europe",
          desc: "日不落帝国", events: ["工业革命", "维多利亚时代"] },
        { name: "法兰西共和国", nameEn: "FRANCE", x: 680, w: 70, start: 1792, end: 2024, color: "#3498db", region: "europe",
          desc: "共和国", events: ["法国大革命", "拿破仑", "欧盟创始国"] },
        { name: "德意志帝国", nameEn: "GERMAN EMPIRE", x: 660, w: 80, start: 1871, end: 1918, color: "#7f8c8d", region: "europe",
          desc: "普鲁士统一德国", events: ["俾斯麦统一", "一战"] },
        { name: "苏联", nameEn: "USSR", x: 760, w: 70, start: 1922, end: 1991, color: "#c0392b", region: "europe",
          desc: "第一个社会主义国家", events: ["十月革命", "二战", "冷战"] },
        { name: "德国", nameEn: "GERMANY", x: 660, w: 80, start: 1990, end: 2024, color: "#2c3e50", region: "europe",
          desc: "统一后的德国", events: ["柏林墙倒塌", "欧盟核心"] },
        { name: "俄罗斯", nameEn: "RUSSIA", x: 760, w: 70, start: 1991, end: 2024, color: "#3498db", region: "europe",
          desc: "俄罗斯联邦", events: ["苏联解体", "普京时代"] },

        // ========== 非洲文明 ==========
        { name: "古埃及", nameEn: "ANCIENT EGYPT", x: 820, w: 80, start: -3100, end: -30, color: "#9b59b6", region: "africa",
          desc: "尼罗河文明", events: ["金字塔", "法老统治", "象形文字"] },
        { name: "库什王国", nameEn: "KUSH", x: 830, w: 50, start: -1070, end: 350, color: "#8e44ad", region: "africa",
          desc: "努比亚王国", events: ["麦罗埃文化"] },
        { name: "迦太基", nameEn: "CARTHAGE", x: 810, w: 60, start: -814, end: -146, color: "#9b59b6", region: "africa",
          desc: "腓尼基殖民地", events: ["汉尼拔", "布匿战争"] },
        { name: "阿克苏姆", nameEn: "AKSUM", x: 830, w: 50, start: 100, end: 940, color: "#8e44ad", region: "africa",
          desc: "埃塞俄比亚古国", events: ["基督教国家"] },
        { name: "加纳帝国", nameEn: "GHANA", x: 810, w: 60, start: 700, end: 1240, color: "#9b59b6", region: "africa",
          desc: "西非黄金帝国", events: ["跨撒哈拉贸易"] },
        { name: "马里帝国", nameEn: "MALI", x: 810, w: 70, start: 1235, end: 1600, color: "#8e44ad", region: "africa",
          desc: "西非最富有帝国", events: ["曼萨穆萨朝圣", "廷巴克图"] },
        { name: "桑海帝国", nameEn: "SONGHAI", x: 820, w: 60, start: 1464, end: 1591, color: "#9b59b6", region: "africa",
          desc: "西非最后大帝国", events: ["索尼阿里"] },
        { name: "埃及", nameEn: "EGYPT", x: 820, w: 60, start: 1953, end: 2024, color: "#8e44ad", region: "africa",
          desc: "现代埃及", events: ["纳赛尔革命", "苏伊士运河"] },

        // ========== 美洲文明 ==========
        { name: "奥尔梅克", nameEn: "OLMEC", x: 920, w: 50, start: -1500, end: -400, color: "#1abc9c", region: "americas",
          desc: "中美洲母文明", events: ["巨石头像"] },
        { name: "玛雅", nameEn: "MAYA", x: 910, w: 70, start: -2000, end: 1500, color: "#16a085", region: "americas",
          desc: "中美洲古典文明", events: ["玛雅历法", "金字塔神庙"] },
        { name: "特奥蒂瓦坎", nameEn: "TEOTIHUACAN", x: 920, w: 50, start: 100, end: 750, color: "#1abc9c", region: "americas",
          desc: "众神之城", events: ["太阳金字塔", "月亮金字塔"] },
        { name: "阿兹特克", nameEn: "AZTEC", x: 910, w: 60, start: 1345, end: 1521, color: "#16a085", region: "americas",
          desc: "墨西哥帝国", events: ["特诺奇蒂特兰", "活人祭祀"] },
        { name: "印加", nameEn: "INCA", x: 920, w: 50, start: 1438, end: 1533, color: "#1abc9c", region: "americas",
          desc: "南美安第斯帝国", events: ["马丘比丘", "结绳记事"] },
        { name: "美国", nameEn: "USA", x: 900, w: 80, start: 1776, end: 2024, color: "#3498db", region: "americas",
          desc: "世界超级大国", events: ["独立宣言", "南北战争", "两次世界大战", "冷战胜利"] },
        { name: "墨西哥", nameEn: "MEXICO", x: 920, w: 50, start: 1821, end: 2024, color: "#27ae60", region: "americas",
          desc: "拉美大国", events: ["独立", "墨西哥革命"] },
        { name: "巴西", nameEn: "BRAZIL", x: 940, w: 50, start: 1822, end: 2024, color: "#f1c40f", region: "americas",
          desc: "南美最大国家", events: ["独立", "经济起飞"] },

        // ========== 蒙古游牧 ==========
        { name: "匈奴", nameEn: "XIONGNU", x: 360, w: 70, start: -209, end: 93, color: "#795548", region: "mongol",
          desc: "北方草原帝国", events: ["冒顿单于", "白登之围"] },
        { name: "鲜卑", nameEn: "XIANBEI", x: 370, w: 50, start: 93, end: 234, color: "#8d6e63", region: "mongol",
          desc: "继匈奴而起", events: ["建立北魏"] },
        { name: "柔然", nameEn: "ROURAN", x: 370, w: 50, start: 330, end: 555, color: "#a1887f", region: "mongol",
          desc: "草原霸主", events: ["与北魏对峙"] },
        { name: "突厥汗国", nameEn: "TURKIC KHAGANATE", x: 350, w: 80, start: 552, end: 744, color: "#795548", region: "mongol",
          desc: "突厥帝国", events: ["控制丝路"] },
        { name: "回鹘", nameEn: "UYGHUR", x: 370, w: 50, start: 744, end: 840, color: "#8d6e63", region: "mongol",
          desc: "回鹘汗国", events: ["安史之乱助唐"] },
        { name: "蒙古帝国", nameEn: "MONGOL EMPIRE", x: 320, w: 140, start: 1206, end: 1368, color: "#2c3e50", region: "mongol",
          desc: "人类历史最大陆地帝国", events: ["成吉思汗", "西征", "四大汗国"] },
        { name: "蒙古", nameEn: "MONGOLIA", x: 370, w: 50, start: 1911, end: 2024, color: "#3498db", region: "mongol",
          desc: "现代蒙古国", events: ["独立", "民主化"] }
    ]
};

// 地区颜色映射
const regionColors = {
    china: "#c23531",
    southAsia: "#3498db",
    westAsia: "#2ecc71",
    europe: "#f39c12",
    africa: "#9b59b6",
    americas: "#1abc9c",
    mongol: "#795548"
};

// 地区中文名称
const regionNames = {
    china: "中华文明",
    southAsia: "南亚文明",
    westAsia: "西亚/波斯文明",
    europe: "欧洲文明",
    africa: "非洲文明",
    americas: "美洲文明",
    mongol: "蒙古游牧文明"
};
